### PR TITLE
Parse and display date and time

### PR DESCRIPTION
**Pull request by slowfranklin**
Signed-off-by: Ralph Boehme slow@samba.org

### CODE REVIEW

**Comment by aaptel** [comment]
thanks! might be more efficient to convert to and store a single timestamp this way the output date format can also be customized (might start to slow things down..)

**Comment by slowfranklin** [comment]
I don't see a need to customize the date format, but we really must have the timestamps from the logs displayed, especially when trying to combine winbind domain child, idmap child and main winbind logs.

**Comment by slowfranklin** [comment]
Rebased my merge branch.

**Comment by aaptel** [comment]
ok!

**Pull request merged**
